Modify : stays view, test.py, function for check date
wecode-bootcamp-korea/28-2nd-StayMemory-backend pull request #14
Opened 2022-01-19 12:19 UTC by coldzero94

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- query string을 통한 findstay 페이지 조건부 필터링

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 체크인, 체크아웃 날짜에 따른 필터링 (예시 - 프론트)
- 예약 내역을 확인하고 예약 가능한 숙소를 표시한다.

2. 주중, 주말에 따른 가격 필터링
- 예약 날짜에 따른 주중, 주말 구분하는 함수에 따른 구현
- 주중, 주말에 따른 가격 최소값, 최대값 산출
- 가격 범위 값 가공하여서 전달

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- q 객체를 통한 filtering 기능을 구현하는데, 많은 조건들이 걸리는 것에 대한 부분을 처음 이행해보는거여서 어려움을 겪었습니다.
- annotate를 통한 column을 추가하고 필요한 쿼리스트링을 만드는 방법에 대해서 알게 되었습니다.
- q 객체 갯수가 늘어남에 따라 if문이 증가하여서 코드의 가독성 및 로딩 속도를 떨어뜨리는 점이 매우 아쉽고 어려웠습니다.
- django queryset 문법을 이해하고 사용하는 방법에 대해서 고민하고 새롭게 사용할 수 있었습니다.(ex: category__name)
- test code의 효율성을 검토하고, 오류를 검증하는 방법에 대해서 새롭게 알 수 있었습니다.
- 코드가 길어질때 함수를 따로 빼서 선언해주고 자료를 따로 필터링 하는 방법에 대해서 알게되었습니다.
- 프론트와 통신시 가공해줘서 넘겨주는 방법에 대해서 고민하고, 새롭게 가격을 직접 string값으로 변환하여서 보내주는 방법에 대해서 배웠습니다.

<br />

## :: 기타 질문 및 특이 사항
- util로 따로 함수를 빼서 날짜확인은 돌아가지만 직접 stays 로 옮겼을때 self 인자 오류가 발생했습니다. 해결 방법에 대해서 좀 더 공부해보겠습니다.

2022-01-19 14:08 UTC, jamessoun93 requested changes

2022-01-19 14:08 UTC, jamessoun93 commented on stays/tests.py
> +class JustTest(TestCase):
테스트케이스 클래스명 변경해주세요.

2022-01-19 14:08 UTC, jamessoun93 commented on stays/tests.py
> +        )
`=`기준 정렬을 다른곳에서는 안하시는 것 같은데 여기도 통일시켜주세요.

2022-01-19 14:08 UTC, jamessoun93 commented on stays/tests.py
> +        response = c.get('/stays/list',{'city':'서울', 'checkin':'2022-1-3', 'checkout':'2022-1-5', 'minprice':'56000', 'maxprice':'70000', 'category':'호텔', 'maxpeople':'4', 'sort':'price'})
`c` 같은 변수명 사용은 지양해주세요 :)

2022-01-19 14:08 UTC, jamessoun93 commented on stays/urls.py
> +    path('/list', StayListView.as_view()),
list가 굳이 필요할까요? `/stays`에 GET 요청이면 충분하고 RESTful 한 URI 설계를 한다고 할때 list라는 파트가 굳이 필요할지 고민해보세요.

2022-01-19 14:08 UTC, jamessoun93 commented on upload.py
> +
upload.py는 git에 올리지 말아주세요.

2022-01-20 01:59 UTC, coldzero94 commented
수정사항 반영해서 수정 하였습니다.

2022-01-20 02:50 UTC, jamessoun93 approved these changes

2022-01-20 02:51 UTC, merged